### ISSUE TITLE
particle glitches

### ISSUE THREAD

**Issue by fleksin** [hoovercj/vscode-power-mode#47] opened 2019-01-30 05:15 UTC
First of all, I love this thing.
But there is a glitch when use particle effect.
Anyone experiencing it?
![particle-glitches](https://user-images.githubusercontent.com/5846753/51959809-143e5d00-2491-11e9-926c-72d140214660.gif)

OS:  macOS mojave
vscode version: 1.30.2

**Comment by wreiske** [comment] 2019-05-22 19:13
I'm getting this too.  All the text shifts from the left to the right when the particles are showing.

![glitchy](https://user-images.githubusercontent.com/6295044/58201866-293f3600-7ca4-11e9-894c-74d8d5c9053c.gif)

**Comment by lackovic** [comment] 2019-10-13 07:37
Confirmed on Windows too.
VsCode version: `1.39.1`

**Comment by PA55ION** [comment] 2020-06-07 18:29
I have the same issue with this as well. Did you guys ever find the solution to this?

**Comment by hoovercj** [comment] 2022-02-27 08:59
Thanks for reporting issues, everyone!

The issue logged by @fleksin seems to be the same as #39 which I am not able to reproduce. If you can still repro it, please add more info to #39 and reopen it.

The issue reported by @wreiske is half "by design" (shake is part of the extension), and half "bug" because it is supposed to shake vertically, too. That is tracked by #71 and will be fixed in the next release, or can be disabled immediately as suggested by @Sokario.

**Closed by hoovercj** 2022-02-27 08:59 UTC
